// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nnberwhazfapkdtdttmh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5uYmVyd2hhemZhcGtkdGR0dG1oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4NTU2OTEsImV4cCI6MjA2MTQzMTY5MX0.D3seh73Y0bUhTmjhJyxlu2fuO4VszxpZLJm3ZbbV7rY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);